apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: config-server
  namespace: petclinic-prod
  labels:
    app.kubernetes.io/name: config-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: config-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: discovery-server
  namespace: petclinic-prod
  labels:
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: discovery-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway
  namespace: petclinic-prod
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: customers-service
  namespace: petclinic-prod
  labels:
    app.kubernetes.io/name: customers-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: customers-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: visits-service
  namespace: petclinic-prod
  labels:
    app.kubernetes.io/name: visits-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: visits-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vets-service
  namespace: petclinic-prod
  labels:
    app.kubernetes.io/name: vets-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vets-service
