apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: petclinic-prod
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: petclinic-prod
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: petclinic-prod
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service
  namespace: petclinic-prod
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: petclinic-prod
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: petclinic-prod
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
  namespace: petclinic-prod
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
  namespace: petclinic-prod
spec:
  replicas: 1
