apiVersion: v1
kind: ResourceQuota
metadata:
  name: petclinic-prod-quota
  namespace: petclinic-prod
  labels:
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/managed-by: kubectl
    environment: prod
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "30"
